export type ValueCard = {
  id: string;
  name: string;
  description: string;
  action: string;
};

export const ALL_VALUES: ValueCard[] = [
  { id: 'v1', name: 'Gia đình', description: 'Gắn kết và chăm sóc những người thân yêu.', action: 'Hãy gọi điện hoặc nhắn tin hỏi thăm một người thân mà bạn yêu quý trong tuần này.' },
  { id: 'v2', name: 'Thành tựu', description: 'Đạt được những mục tiêu quan trọng và được công nhận.', action: 'Viết ra 3 mục tiêu nhỏ bạn có thể hoàn thành ngay hôm nay và đánh dấu tích khi xong.' },
  { id: 'v3', name: 'Tự do', description: 'Sống độc lập, không bị ràng buộc hay định kiến.', action: 'Dành ra 30 phút làm một điều gì đó hoàn toàn ngẫu hứng, không có trong kế hoạch.' },
  { id: 'v4', name: 'Sức khỏe', description: 'Duy trì thể chất và tinh thần khỏe mạnh.', action: 'Thực hiện 15 phút giãn cơ hoặc đi bộ nhẹ nhàng vào cuối ngày hôm nay.' },
  { id: 'v5', name: 'Tình yêu', description: 'Trải nghiệm sự lãng mạn và sự thấu cảm sâu sắc.', action: 'Nói một lời khen ngợi chân thành với người bạn yêu thương hoặc trân trọng.' },
  { id: 'v6', name: 'Khám phá', description: 'Học hỏi điều mới, du lịch và phiêu lưu.', action: 'Tìm đọc một bài viết hoặc xem một video về một chủ đề bạn chưa từng biết đến.' },
  { id: 'v7', name: 'Sự nghiệp', description: 'Xây dựng đường hướng công việc vững chắc.', action: 'Cập nhật lại CV hoặc dành 20 phút học một kỹ năng nhỏ phục vụ cho công việc.' },
  { id: 'v8', name: 'Bình an', description: 'Sống thanh thản, ít lo âu và không vướng bận.', action: 'Thực hành 5 phút ngồi yên tĩnh, chỉ tập trung vào hơi thở mỗi sáng thức dậy.' },
  { id: 'v9', name: 'Chân thành', description: 'Sống thật với chính mình và mọi người xung quanh.', action: 'Hôm nay, hãy thử nói lên suy nghĩ thực sự của mình ở một thời điểm bạn định im lặng.' },
  { id: 'v10', name: 'Sáng tạo', description: 'Mang đến những ý tưởng mới mẻ và độc đáo.', action: 'Thử làm một việc quen thuộc theo một cách hoàn toàn mới (ví dụ: đi đường khác để về nhà).' },
  { id: 'v11', name: 'Tôn trọng', description: 'Đối xử tử tế và giữ được sự tôn trọng từ người khác.', action: 'Lắng nghe trọn vẹn một người khác nói mà không ngắt lời hay phán xét.' },
  { id: 'v12', name: 'Công bằng', description: 'Duy trì lẽ phải và xử lý mọi việc bình đẳng.', action: 'Bảo vệ hoặc lên tiếng ủng hộ một người/khiến một quyết định trở nên khách quan hơn.' },
  { id: 'v13', name: 'Dũng cảm', description: 'Đối mặt với nỗi sợ và đứng lên bảo vệ điều đúng đắn.', action: 'Làm một việc nhỏ mà bạn thường né tránh vì cảm giác không thoải mái.' },
  { id: 'v14', name: 'Niềm vui', description: 'Tận hưởng cuộc sống và mang lại tiếng cười.', action: 'Xem một video hài hước hoặc rủ một người bạn làm điều gì đó mang tính giải trí.' },
  { id: 'v15', name: 'Lòng trắc ẩn', description: 'Thấu hiểu và giúp đỡ những ai đang gặp khó khăn.', action: 'Làm một việc tốt nhỏ bé, ẩn danh cho một người bất kỳ.' },
  { id: 'v16', name: 'Thống nhất', description: 'Sống nhất quán giữa lời nói và hành động.', action: 'Kiểm tra xem cam kết gần đây nhất của bạn đã được thực hiện hay chưa, và bắt tay vào làm nó.' },
  { id: 'v17', name: 'Gắn kết', description: 'Trở thành một phần của cộng đồng hoặc tập thể.', action: 'Tham gia hoặc tương tác tích cực trong một nhóm cộng đồng mà bạn quan tâm.' },
  { id: 'v18', name: 'Bao dung', description: 'Sẵn sàng tha thứ cho lỗi lầm của bản thân và người khác.', action: 'Nhắc nhở bản thân rằng "Mọi người đều có thể sai" khi ai đó làm bạn phật ý.' },
  { id: 'v19', name: 'Thấu cảm', description: 'Hiểu và chia sẻ cảm xúc với người khác.', action: 'Khi ai đó tâm sự, hãy thử diễn đạt lại cảm xúc của họ thay vì vội vàng đưa ra lời khuyên.' },
  { id: 'v20', name: 'Tri thức', description: 'Theo đuổi sự hiểu biết và trí tuệ.', action: 'Đọc 10 trang của một cuốn sách hoặc tài liệu chuyên ngành.' },
  { id: 'v21', name: 'Thẳng thắn', description: 'Nói lên sự thật một cách cởi mở và trực tiếp.', action: 'Góp ý chân thành, mang tính xây dựng cho một vấn đề mà bạn thấy có thể cải thiện.' },
  { id: 'v22', name: 'Kiên nhẫn', description: 'Giữ được bình tĩnh trước khó khăn và thử thách.', action: 'Khi phải chờ đợi (xếp hàng, kẹt xe), hãy tận dụng thời gian đó để thả lỏng vai và thư giãn.' },
  { id: 'v23', name: 'Quyền lực', description: 'Tạo ra sức ảnh hưởng và dẫn dắt người khác.', action: 'Đề xuất một giải pháp thực tế cho một vấn đề chung trong nhóm của bạn.' },
  { id: 'v24', name: 'An toàn', description: 'Tránh xa nguy hiểm, ưu tiên sự vững chắc.', action: 'Rà soát lại tài chính hoặc lên một bản kế hoạch dự phòng cho tháng tới.' },
  { id: 'v25', name: 'Tâm linh', description: 'Hướng về các niềm tin thiêng liêng cao cả.', action: 'Dành 10 phút cầu nguyện, thiền định hoặc kết nối với đức tin của bạn.' },
  { id: 'v26', name: 'Thịnh vượng', description: 'Tích lũy tài sản và tận hưởng sự dư dả.', action: 'Bắt đầu tiết kiệm một khoản nhỏ hoặc liệt kê các cách để tối ưu hóa nguồn thu.' },
  { id: 'v27', name: 'Kỷ luật', description: 'Tuân thủ các nguyên tắc do mình đặt ra.', action: 'Dọn dẹp lại không gian làm việc hoặc hoàn thành một thói quen nhỏ bạn thường hay bỏ lỡ.' },
  { id: 'v28', name: 'Biết ơn', description: 'Trân trọng những gì mình đang có.', action: 'Viết ra 3 điều nhỏ bé trong ngày hôm nay khiến bạn cảm thấy biết ơn.' },
  { id: 'v29', name: 'Trách nhiệm', description: 'Đối diện và đảm nhận hậu quả hành động của mình.', action: 'Nhận lỗi về một thiếu sót nhỏ và chủ động đề xuất cách khắc phục.' },
  { id: 'v30', name: 'Hoàn hảo', description: 'Làm mọi thứ ở tiêu chuẩn cao nhất có thể.', action: 'Rà soát lại một dự án hoặc công việc đang làm để tăng thêm sự tỉ mỉ, trọn vẹn.' },
  { id: 'v31', name: 'Độc lập', description: 'Tự lo liệu và không dựa dẫm vào ai.', action: 'Tự mình giải quyết một công việc nhỏ mà bạn thường nhờ người khác.' },
  { id: 'v32', name: 'Mạo hiểm', description: 'Chấp nhận rủi ro để đổi lấy phần thưởng lớn.', action: 'Đăng ký một thử thách nhỏ hoặc bước ra khỏi vùng an toàn trong một quyết định hôm nay.' },
  { id: 'v33', name: 'Cống hiến', description: 'Góp sức vào những mục tiêu lớn hơn cá nhân.', action: 'Ủng hộ một quỹ từ thiện hoặc đóng góp một kiến thức/kỹ năng cho cộng đồng miễn phí.' },
  { id: 'v34', name: 'Tiện nghi', description: 'Tận hưởng một cuộc sống thoải mái, dễ dàng.', action: 'Sắp xếp lại góc thư giãn hoặc mua một món đồ nhỏ giúp cuộc sống hàng ngày tiện lợi hơn.' },
  { id: 'v35', name: 'Uy tín', description: 'Giữ lời hứa và được nhiều người tin tưởng.', action: 'Thực hiện đúng một cam kết bạn đã nói với người khác trong hôm nay.' },
  { id: 'v36', name: 'Hợp tác', description: 'Làm việc thuận hòa cùng người khác để đạt mục tiêu chung.', action: 'Hỏi một người đồng nghiệp/bạn bè xem bạn có thể hỗ trợ họ điều gì không.' },
  { id: 'v37', name: 'Khôn khéo', description: 'Uyển chuyển trong giao tiếp và xử lý tình huống.', action: 'Trong cuộc trò chuyện tới, hãy quan sát ngôn ngữ cơ thể của người đối diện để phản hồi phù hợp.' },
  { id: 'v38', name: 'Say mê', description: 'Dành toàn bộ năng lượng cho điều mình cực kỳ yêu thích.', action: 'Dành 1 giờ đồng hồ chìm đắm hoàn toàn vào sở thích cá nhân mà không để bị phân tâm.' },
  { id: 'v39', name: 'Bảo vệ môi sinh', description: 'Tôn trọng và giữ gìn thế giới tự nhiên.', action: 'Giảm bớt việc sử dụng nhựa dùng một lần hoặc chăm sóc một chậu cây nhỏ.' },
  { id: 'v40', name: 'Thẩm mỹ', description: 'Thưởng thức và tạo ra cái đẹp.', action: 'Bật một bản nhạc hay, cắm một lọ hoa hoặc sắp xếp lại không gian cho thật đẹp mắt.' },
  { id: 'v41', name: 'Tĩnh lặng', description: 'Ưu tiên những nơi chốn và khoảnh khắc không ồn ào.', action: 'Tắt màn hình điện thoại và ngồi yên trong không gian yên tĩnh 10 phút.' },
  { id: 'v42', name: 'Mới mẻ', description: 'Trải nghiệm những sự thay đổi để không nhàm chán.', action: 'Thay đổi lộ trình đi làm hoặc thử một món ăn bạn chưa từng ăn.' },
  { id: 'v43', name: 'Lạc quan', description: 'Nhìn nhận cuộc đời qua lăng kính tích cực.', action: 'Lật ngược một vấn đề đang làm bạn lo lắng để tìm ra một khía cạnh tích cực, bài học trong đó.' },
  { id: 'v44', name: 'Hiếu thảo', description: 'Kính trọng và biết ơn đấng sinh thành.', action: 'Hỏi thăm sức khỏe của cha mẹ hoặc chuẩn bị cho họ một sự bất ngờ nhỏ.' },
  { id: 'v45', name: 'Logic', description: 'Hành xử dựa trên lý trí, khoa học và dữ kiện.', action: 'Giải quyết một vấn đề phức tạp bằng cách lấy giấy bút vẽ sơ đồ tư duy.' },
  { id: 'v46', name: 'Khoan dung', description: 'Lòng rộng mở với sự đa dạng và khác biệt.', action: 'Tìm hiểu một quan điểm trái ngược với bạn với một tấm lòng cởi mở, không thành kiến.' },
  { id: 'v47', name: 'Dẻo dai', description: 'Khả năng phục hồi nhanh chóng sau thất bại.', action: 'Nhắc lại một thất bại trong quá khứ và công nhận sự trưởng thành của bạn từ đó.' },
  { id: 'v48', name: 'Thực tế', description: 'Nhìn vấn đề đúng như bản chất, không viển vông.', action: 'Đánh giá lại một mục tiêu và điều chỉnh nó cho vừa vặn với nguồn lực hiện tại.' },
  { id: 'v49', name: 'Hòa giải', description: 'Làm người đứng giữa kết nối những xung đột.', action: 'Giúp giải quyết một bất đồng nhỏ giữa hai người bạn hoặc đồng nghiệp.' },
  { id: 'v50', name: 'Gọn gàng', description: 'Duy trì sự trật tự, ngăn nắp trong mọi mặt.', action: 'Dọn dẹp ví tiền, túi xách hoặc màn hình máy tính của bạn cho thật ngăn nắp.' },
];
